#!/bin/bash

# Script for running the selfhosted tests on QPUs directly from GitHub
# Tests need to be copied to /tmp/ because coverage does not work with NFS

TMP_DIR=$(mktemp -d selfhosted.qibojit.XXXXXXX)

cp -r src/qibojit/tests "$TMP_DIR"
cp pyproject.toml "$TMP_DIR/"
cd "$TMP_DIR/tests"

source /nfs/users/github/actions-runner/_work/qibojit/qibojit/testenv/bin/activate

pytest --gpu_only

pytest_status=$?

if [[ $pytest_status -ne 0 ]]
    then
        exit $pytest_status
fi

cd -

mv "$TMP_DIR/tests/coverage.xml" .
mv "$TMP_DIR/tests/htmlcov" .
rm -r "$TMP_DIR"
