# A single CI script with github workflow
name: Tests

on:
  push:
  merge_group:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13.5"]
    uses: qiboteam/workflows/.github/workflows/rules-poetry.yml@v1
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      poetry-extras: --with test
    secrets: inherit
