# A single CI script with github workflow
name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, '3.10', '3.11']
    uses: qiboteam/workflows/.github/workflows/rules.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      environment: "qibojit"
    secrets: inherit
